
INSERT INTO DND_ATTENDANCE_HISTORY(ID,PLAYERS_ATTENDED,PLAYERS_EXCUSED,PLAYERS_NO_SHOW_OR_NO_RESPONSE,PLAYERS_NAMES_ATTENDED,PLAYERS_NAMES_EXCUSED,PLAYERS_NAMES_NO_SHOW_OR_NO_RESPONSE,WEEK_OF_ATTENDANCE)
VALUES(1,'5','3','1','Nick | Anthony | Jared | Shane | Pat','Ty | Thai | Brendan','Gary','11/14/22');

INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(1,'Zach','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(2,'Anthony','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(3,'Nick','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(4,'Ty','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(5,'Thai','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(6,'Pat','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(7,'Shane','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(8,'Jared','N','N','Y');
INSERT INTO DND_ATTENDANCE_INFO(ID,PLAYERS_NAME,ATTENDING,EXCUSED,NO_SHOW_OR_NO_RESPONSE) VALUES(9,'Gary','N','N','Y');

INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(1,'Zach','Dungeon Master','448620591944171521');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(2,'Anthony','Yelgeiros','416342612484554752');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(3,'Nick','Doug','258377595652014080');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(4,'Ty','Jimbo','154404187256389632');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(5,'Thai','Artemis','671548924426715152');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(6,'Pat','Sudoku','330537143485333504');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(7,'Shane','Uthal','274916008643526666');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(8,'Jared','Digby','204074647245815808');
INSERT INTO DND_PLAYERS_INFO(ID,PLAYERS_NAME,PLAYERS_NICKNAME,DISCORD_USER_ID) VALUES(9,'Gary','Metra','196742001306107915');